#
# A GitHub workflow to build a container for each semantically versioned tag (i.e. vX.Y.Z).
#
# help:
# - tagging info: https://github.com/docker/build-push-action/blob/v2/docs/advanced/tags-labels.md
# - original gist: https://gist.github.com/robb-j/049217ca8cecf4e214b8b82123f7371b
#

name: Containers

on:
  push:
    tags: [v*]

jobs:
  build-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate cli metadata
        id: cli_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/digitalinteraction/maps.openlab.dev/cli
          tags: type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build cli
        uses: docker/build-push-action@v6
        with:
          file: cli/Dockerfile
          push: true
          tags: ${{ steps.cli_meta.outputs.tags }}
          labels: ${{ steps.cli_meta.outputs.labels }}
